name: Workflow test
run-name: ${{ github.actor }} running lint action by ${{ github.event_name }}
on:
  push:
  workflow_dispatch:
env:
  NPM_PACKAGE_NAME: vue
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - run: echo "NPM_PACKAGE_VERSIONS=$('npm view ${{env.NPM_PACKAGE_NAME}} versions')" >> $GITHUB_ENV
      - run: echo ${{env.NPM_PACKAGE_VERSIONS}}

