name: Workflow test
run-name: ${{ github.actor }} running lint action by ${{ github.event_name }}
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - run: echo "NPM_PACKAGE_NAME=$(node -p 'require("./package.json").name')" >> $GITHUB_ENV
      - run: echo ${{env.NPM_PACKAGE_NAME}}
      - run: echo ${{env.CI}}

